[package]
name = "stm32-usbd"
version = "0.1.1"
edition = "2018"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>", "Vadim Kaushan <admin@disasm.info>", "Nicolas Stalder <n@stalder.io>", "Jonas Martin <lichtfeind@gmail.com>"]
description = "'usb-device' implementation for STM32 microcontrollers"
license = "MIT"
repository = "https://github.com/Disasm/stm32-usbd"
readme = "README.md"
keywords = ["no-std", "embedded", "usb"]

[dependencies]
vcell = "0.1.0"
cortex-m = "0.5.8"
stm32f0xx-hal = { version = "0.14.1", features = ["rt"], optional = true }
stm32f1xx-hal = { version = "0.3", features = ["rt"], optional = true }
stm32f3xx-hal = { version = "0.1.4", features = ["rt"], optional = true }
stm32l4xx-hal = { version = "0.4", features = ["rt"], optional = true }
usb-device = "0.2.0"

[dev-dependencies]
cortex-m-rt = "0.6.7"
cortex-m-rtfm = "0.4.0"
panic-semihosting = "0.5.1"

[features]
default = []
stm32f0 = ['stm32f0xx-hal']
stm32f103xx = ['stm32f1xx-hal', 'stm32f1xx-hal/stm32f103']
stm32f303xc = ['stm32f3xx-hal', 'stm32f3xx-hal/stm32f303']
stm32l4x2xx = ['stm32l4xx-hal', 'stm32l4xx-hal/stm32l4x2']

[package.metadata.docs.rs]
features = ["stm32f103xx"]
